services:
  db:
    container_name: "talkio-pg"
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: talkio
    ports:
      - "5432:5432"
    volumes:
      - ./apps/server/docker/setup.sql:/docker-entrypoint-initdb.d/init.sql