services:
  postgres:
    container_name: talkio-postgres
    image: bitnami/postgresql:17.4.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=talkio
    volumes:
      - postgres_data:/bitnami/postgresql

  redis:
    container_name: talkio-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
